# Generated by Django 3.0.7 on 2020-07-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paymenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offering.fund')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
                ('mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offering.paymenttype')),
            ],
        ),
    ]
