# Generated by Django 3.0.7 on 2020-07-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0001_initial'),
        ('members', '0002_auto_20200702_0222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='member',
        ),
    ]
